version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# If using Sphinx (default)
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx conf.py

# If using MkDocs instead
# mkdocs:
#   configuration: mkdocs.yml

# Optional: Install Python dependencies
python:
  install:
    - requirements: docs/requirements.txt  # If you have one
