version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Install Python dependencies
python:
  install:
    - requirements: docs/requirements.txt  # Path to your requirements file
    - method: pip
      path: .  # Installs your project in "editable" mode (if needed)

sphinx:
  configuration: docs/conf.py  # Path to Sphinx config
  fail_on_warning: true  # Optional: Strict mode to catch issues early
